export const AUTH_ACTION_TYPES = {
    USERNAME_TO_USER: "USERNAME_TO_USER",
    LOGIN_TO_USER: "LOGIN_TO_USER",
    LOGOUT_TO_USER: "LOGOUT_TO_USER",
    PASSWORD_TO_USER: 'PASSWORD_TO_USER',
    ROLES_TO_USER: 'ROLES_TO_USER',
    ACCESSTOKEN_BY_USER: 'ACCESSTOKEN_BY_USER',
    
}